### ISSUE TITLE
executable file not opening in windows 10

### ISSUE THREAD

**Issue by Vishal-09-00** [Cyb3r-Jak3/cloudflare-utils#10]
I downloaded the latest version in order to bulk delete the DNS records but I am not able to make it work as it does not start at all.

**Comment by Cyb3r-Jak3** [comment]
How are you trying to run the program? Are you getting any error? It is a CLI application, so you would need to run in a PowerShell window.

**Comment by Vishal-09-00** [comment]
> How are you trying to run the program? Are you getting any error? It is a CLI application, so you would need to run in a PowerShell window.

I downloaded the latest version for windows 10 and extracted the folder, and then I am trying to run the .exe file but nothing happens. If I am doing this the wrong way, please guide me.😃

**Comment by Vishal-09-00** [comment]
> How are you trying to run the program? Are you getting any error? It is a CLI application, so you would need to run in a PowerShell window.

I downloaded the latest version for windows 10 and extracted the folder, and then I am trying to run the .exe file but nothing happens. If I am doing this the wrong way, please guide me.😃

**Comment by Vishal-09-00** [comment]
> How are you trying to run the program? Are you getting any error? It is a CLI application, so you would need to run in a PowerShell window.

![utils](https://user-images.githubusercontent.com/75847766/202495616-39ffa93b-d736-4c9c-a0b9-b9d85a090486.png)

after opening the .exe using powershell I am getting this error. Please mention the correct usage for the same.

**Comment by Cyb3r-Jak3** [comment]
@Vishal-09-00 For DNS cleaner you need to run it like `.\cloudflared-utils.exe --api-token <you token> dns_cleaner` which will download your current DNS records. You then edit and re-run the command to have the records be updated.
You can run .\cloudflare-utils.txt dns_cleaner --help` for more info on the command or visit the [docs ](https://cloudflare-utils.cyberjake.xyz/dns-cleaner/).

**Comment by Cyb3r-Jak3** [comment]
I'm going to close this issue as stale. If happens again then please make a new issue.
