### ISSUE TITLE
no DNS file found

### ISSUE THREAD

**Issue by ExistentialDysfunction** [Cyb3r-Jak3/cloudflare-utils#24]
Hello, I am pretty sure I did everything correctly, but I keep getting this error when I try to upload back the edited .yml file:
"FATA[0000] Error running app error="no DNS file found at './dns-records.yml'"

Tried from both windows and linux, keep getting the same error.

**Comment by Cyb3r-Jak3** [comment]
I would check to make sure that the file exists in the same directory you are running the command. If your file name is different then you can change the expected file name with `--dns-file`

**Comment by toobeeh** [comment]
having the same issue. i haven't changed the file name; even if i do and specify it at the upload, it's not recognized.
the file exists in the same directory, and the executable is being run in the same dir too.

**Comment by Cyb3r-Jak3** [comment]
What version are you running? I would recommend the latest [release candidate](https://github.com/Cyb3r-Jak3/cloudflare-utils/releases/tag/v1.1.0-rc4)
Can you run the command with the `--debug` flag so the command would look like
`./cloudflare-utils --api-token <token> --debug --zone-name <our zone name> dns-cleaner`

**Comment by toobeeh** [comment]
I didn't realize there were newer releases available, so i used 1.0.0. 
The linked release runs without problems. 
Thanks a lot for this tool, it saves a lot of trouble!

**Comment by Cyb3r-Jak3** [comment]
@ExistentialDysfunction are you still having the issue on that latest version?

**Comment by Cyb3r-Jak3** [comment]
Closing this as stale.
