### ISSUE TITLE
Not working for country code TLD

### ISSUE THREAD

**Issue by gtu-myowin** [Cyb3r-Jak3/cloudflare-utils#39]
Hi, thanks for the nice software but it is not working for domains with country code or at least it is not working for some. Please see the screenshot below. When I try with .com domain, it works. Please let me know if you need further information.

<img width="919" alt="Screenshot 2023-09-24 at 11 39 05 AM" src="https://github.com/Cyb3r-Jak3/cloudflare-utils/assets/2696343/a13a1287-b52c-4ead-a2d8-b2ff2d74aba0">

**Comment by Cyb3r-Jak3** [comment]
Thanks for the report.
Just to confirm, the zone name matches what you have configured in the dashboard and the api token has permissions to edit the zone?

In the meantime, you should be able to use your zone ID instead, which you can get from https://dash.cloudflare.com/?to=/:account/:zone.

**Comment by gtu-myowin** [comment]
Hi, sorry it was my mistake. The cloudflare account was different and thus the credential was too. I am sorry and thank you for your time.
