### ISSUE TITLE
DNS Purge Not Working

### ISSUE THREAD

**Issue by smashedr** [Cyb3r-Jak3/cloudflare-utils#60]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of cloudflare-utils and it is still present.

### cloudflare-utils version

cloudflare-utils version  (built 2023-08-20 22:00 UTC with go1.20.7)

### Go environment

$ docker run cyb3rjak3/cloudflare-utils --api-token  XXX  --zone-name  smwc.world dns-purge

About to remove 999 records.
Continue (y/n): Error running app: EOF

### Expected output

I expect the program to work. 

### Actual output

Continue (y/n): Error running app: EOF

### Steps to reproduce

I just run the `dns-purge` command.

### Link to debug output

Incorrect Usage: flag provided but not defined: -trace

**Comment by Cyb3r-Jak3** [comment]
I suspect that this is due to docker running not interactively. If you are okay skipping the confirmation prompt, then add `--conform` to your command so it would look like `docker run cyb3rjak3/cloudflare-utils --api-token XXX --zone-name smwc.world dns-purge --confirm`

**Comment by Cyb3r-Jak3** [comment]
This works how'd I would expect it to do, but I'll add a note to the doc to help for the future.
